import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "eth-thor bridge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <body className={inter.className}>
          <div className="relative sm:-8 p-4 bg-[#13131a] min-h-screen flex flex-row">
            <div className="sm:flex hidden mr-10 relative">
              <Sidebar />
            </div>
            <div className="flex-1 max-sm:w-full max-w-[1280px] mx-auto sm:pr-5">
              {children}
            </div>
          </div>
        </body>
      </body>
    </html>
  );
}
